### PR TITLE
Replace makefile by npm

### PR DESCRIPTION
**Pull request by MattiSG**

### CODE REVIEW

**Comment by MattiSG** [comment]
We're stuck because `react-scripts` makes the assumption that it is at the root of the project, which is not currently the case as the frontend root is `front`.

Options:
- Move the `front` hierarchy to the root of the project.
- [`eject`](https://www.npmjs.com/package/react-scripts#converting-to-a-custom-setup) `react-scripts` and define the path in the generated webpack config.

Just `cd front && react-scripts start` in the `npm start` script doesn't work.

**Comment by ThibautGery** [comment]
I vote for the first option, @Flightan ? @tmerlier ?

**Comment by ThibautGery** [comment]
@MattiSG do you plan to do it ? 
There might be a hard merge/rebase with #38 we should wait for the PR to be merged or closed

**Comment by MattiSG** [comment]
Was waiting for your pings to reply. Shouldn't be so hard if everything is moved with `git mv`.

**Comment by ThibautGery** [comment]
If all the files are moved with `git mv` to two different locations, it might cause some problems

**Comment by MattiSG** [comment]
As long as they are not edited, it's not very hard.

**Comment by ThibautGery** [comment]
There is some modification since we have to change the `import`. The good news is : It's already merged

**Comment by tmerlier** [comment]
Move the front hierarchy to the root of the project.

**Comment by Flightan** [comment]
Evidemment maintenant qu'on casse les tests si cairo n'est pas installé, les tests pètent parce que cairo n'est pas installé.

**Comment by MattiSG** [comment]
> les tests pètent parce que cairo n'est pas installé

Mais… je croyais d'après #47 que `cairo` était nécessaire pour les tests 😕

**Pull request merged**
